pipeline {
    agent any

    stages {
        stage('Unit tests- Backend') {
            agent{
                docker{
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh '''
                        mkdir -p "$WORKSPACE/.gocache/pkg/mod"
                        mkdir -p "$WORKSPACE/.gopath"
                        GOCACHE="$WORKSPACE/.gocache" \
                        GOMODCACHE="$WORKSPACE/.gocache/pkg/mod" \
                        GOPATH="$WORKSPACE/.gopath" \
                        go test -v ./...
                    '''
                }
            }
        }

        stage('Unit tests- Frontend') {
            agent{
                docker{
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test
                    '''
                }
            }
        }
    }
}