pipeline {
    agent any

    stages {
        stage('Unit tests- Backend') {
            agent{
                docker{
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                    args '-u root'
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'GOCACHE=$WORKSPACE/.gocache go test -v ./...'
                }
            }
        }
    }
}